name: Hello world

on:
    push:
        branches:
            main

jobs:
    hello_world_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Now it is
              run: |
                date
            - name: List directory
              run: |
                ls -l